### ISSUE TITLE
didn't work in anki 2.1.45

### ISSUE THREAD

**Issue by justpeanuts** [aleksandar-j/set-card-ease#1]
what i did:
selected cards, clicked set ease, entered 250 in the text box, clicked okay... then a pop-up with just an exclamation icon (and nothing else), showed up .. and the ease of the selected cards remained same as before. 

DEBUG INFO:
    
    Anki 2.1.45 (355e66e8) Python 3.8.1 Qt 5.15.1 PyQt 5.15.1
    Platform: Linux
    Flags: frz=True ao=True sv=2
    Add-ons, last update check: 2022-04-08 21:48:45
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    '' ['set-card-ease-master', 0, 'None', '']
    Advanced Browser ['874215009', 2020-11-08T16:33, 'None', '']
    Anki Simulator ['817108664', 2021-08-08T00:54, 'None', '']
    Anki Zoom ['538879081', 2020-04-04T05:50, 'v1.1.3', mod]
    AwesomeTTS - Add speech to your flashcards ['1436550454', 2022-02-20T08:53, 'None', '']
    Card Info During Review ['2179254157', 2020-07-09T05:36, 'None', '']
    Color Confirmation ['1084228676', 2020-03-14T17:43, 'None', '']
    Customize Keyboard Shortcuts ['24411424', 2022-04-05T09:32, 'None', mod]
    Frozen Fields ['516643804', 2020-03-01T09:42, 'None', '']
    Image Occlusion Enhanced for Anki 21 alpha ['1374772155', 2020-04-28T07:51, 'None', '']
    Legacy ReMemorize ['323586997', 2020-11-20T10:57, 'None', mod]
    Life Drain ['715575551', 2022-02-13T18:45, 'None', '']
    Links between notes cards to open browser and previewer ['1126950429', 2020-12-23T10:21, 'None', mod]
    Opening the same window multiple time ['354407385', 2020-05-16T06:29, 'None', '']
    Puppy Reinforcement ['1722658993', 2020-03-03T01:53, 'None', '']
    Review Heatmap ['review_heatmap', 2020-04-30T18:53, 'None', '']
    Ze Add Note Id ['886709118', 2020-07-30T21:42, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    1084228676 1126950429 1374772155 1436550454 1722658993 2179254157 24411424 323586997 354407385 516643804 538879081 715575551 817108664 874215009 886709118
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Pop-up Dictionary beta ['153625306', 2019-03-23T23:02, 'None', '']
    Searching PDF Reading  Note-Taking in Add Dialog ['1781298089', 2021-09-17T15:54, 'None', mod]
    Undelete deleted note ['912930620', 2019-05-01T12:23, 'None', mod]
    Zoom 21 ['1846592880', 2020-01-12T22:56, 'None', '']

**Comment by aleksandar-j** [comment]
Looks like Anki 2.1.45 doesn't have update_cards method... I pushed some changes to this repository but have not yet updated the files at AnkiWeb. Can you try this update and confirm that it works on 2.1.45 now? The only changed file is [set_card_ease.py](https://github.com/aleksandar-j/set-card-ease/blob/master/set_card_ease.py) so you can just download and replace that one.
